import { format } from 'date-fns';
import { VariablesTypes } from 'dhis2-semis-types'

export const staticForm = (attendaceStatus: any[]) => {
  return [
    {
      required: false,
      name: "registeringSchool",
      labelName: "Selected School",
      valueType: "TEXT",
      options: undefined,
      disabled: true,
      pattern: "",
      visible: true,
      description: "Selected School",
      searchable: false,
      error: false,
      programStage: "",
      content: "",
      id: "SelectedSchool",
      displayName: "Selected School",
      header: "Selected School",
      type: VariablesTypes.DataElement,
      assignedValue: undefined
    },
    {
      required: true,
      name: "attendanceDay",
      labelName: "Attendance date",
      valueType: "DATE",
      options: undefined,
      disabled: true,
      pattern: "",
      visible: true,
      description: "Attendance date",
      searchable: false,
      error: false,
      programStage: "",
      content: "",
      id: "attendanceDay",
      displayName: "Attendance date",
      header: "Enrollment date",
      type: VariablesTypes.DataElement,
      assignedValue: format(new Date(), "yyyy-MM-dd")
    },
    {
      required: false,
      name: "studentsNumber",
      labelName: "Number of Learners",
      valueType: "NUMBER",
      options: undefined,
      disabled: true,
      pattern: "",
      visible: true,
      description: "Number of Learners",
      searchable: false,
      error: false,
      programStage: "",
      content: "",
      id: "studentsNumber",
      displayName: "Number of Learners",
      header: "Number of Learners",
      type: VariablesTypes.DataElement,
      assignedValue: undefined,
    },
    {
      required: false,
      name: "status",
      labelName: "Attendance option:",
      valueType: "LIST",
      options: { optionSet: { options: attendaceStatus?.map((x) => ({ ...x, value: x.code })) } },
      disabled: false,
      pattern: "",
      visible: true,
      description: "Attendance option:",
      searchable: false,
      error: false,
      programStage: "",
      content: "",
      id: "status",
      displayName: "Attendance option:",
      header: "Attendance option:",
      type: VariablesTypes.DataElement,
      assignedValue: undefined,
    }
  ]
}
